## Operating sys options : centos7, rhel8, rhel8, ubuntu20, ubuntu22
OperatingSystem: rhel8

# number of nodes / containers in cluster
nodes: 3                              # Upto 7 nodes

# "AMBARI,HDFS,ZOOKEEPER,YARN,MAP-REDUCE,INFRA-SOLR,HIVE,TEZ,HBASE,SQOOP,RANGER,RANGER-KMS,DRUID,SPARK2,OOZIE"
Components: "AMBARI,HDFS,ZOOKEEPER,YARN,MAP-REDUCE,INFRA-SOLR,HIVE,TEZ,HBASE"

AmbariVersion: "2.7.9.1-1"
AmbariUrl: "https://mirror.odp.acceldata.dev/v2/ambari/python3/jdk11/2.7.9.1-1/releases/rhel8/"

OdpVersion: "3.3.6.1-1"
OdpUrl: "https://mirror.odp.acceldata.dev/v2/odp/python3/jdk11/3.3.6.1-1/releases/rhel8/"

UtilsUrl: "https://mirror.odp.acceldata.dev/v2/odp-utils/centos8/"
MpackUrl: "https://mirror.odp.acceldata.dev/v2/odp/python3/jdk11/3.3.6.1-1/mpacks/"


Database: "mysql"            # mysql, postgres, oracle, mariadb
Kerberos: "Yes"                           # Yes or No
SSL: "No"

## Optional
resources:
  requests:
    cpu: "2"
    memory: "16Gi"
  limits:
    cpu: "6"
    memory: "32Gi"