# There are 4 images
#For Rocky 8 
#Python2 : sehajsandhu/odp_rl8_py2:v1
#Python3 : sehajsandhu/odp_rl8_py311:v1
#
#For ubuntu 20
#Python2 : sehajsandhu/odp_ub20_py2:v1
#Python3 : sehajsandhu/odp_ub20_py311:v1


image: sehajsandhu/odp-rocky-py2:v4
nodes: 3                               # Upto 4 nodes
components: ""                         # "AMBARI,HDFS,ZOOKEEPER,YARN,MAP-REDUCE,INFRA-SOLR,HIVE,TEZ,HBASE,SQOOP,RANGER,RANGER-KMS,DRUID,SPARK2,OOZIE"
ambariVersion: ""
ambariUrl: ""
odpVersion: ""
odpUrl: ""          
jdkVersion: ""                         # 8 or 11
kerberos: ""                           # YES or No
