apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: http
      port: 8080
      targetPort: 8080
    - name: https
      port: 8443
      targetPort: 8443
