apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-command"
  labels:
    app: "{{ .Release.Name }}"
data:
  bashexec.sh: |
    #!/bin/bash
    bash ~/basher.sh '{{ .Release.Name }}' '{{ .Values.jdkVersion }}' '{{ .Values.nodes }}' '{{ .Values.kerberos }}' '{{ .Values.components }}' '{{ .Values.odpVersion }}' '{{ .Values.ambariVersion }}' '{{ .Values.odpUrl }}' '{{ .Values.ambariUrl }}'

