apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
spec:
  serviceName: "{{ .Release.Name }}"
  replicas: {{ .Values.nodes }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}"
    spec:
      containers:
        - name: trial
          image: "{{ .Values.image }}"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /sys/fs/cgroup
              name: cgroup
              readOnly: true
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus-socket
              readOnly: true
            - mountPath: /run
              name: run-tmpfs
            - mountPath: /tmp
              name: tmpfs
            - mountPath: /config
              name: command-configmap
              readOnly: true
          resources:
            requests:
              cpu:    {{ default (ternary "2" "6" (eq .Values.nodes 3)) .Values.resources.requests.cpu }}
              memory: {{ default (ternary "12Gi" "16Gi" (eq .Values.nodes 3)) .Values.resources.requests.memory }}
              ephemeral-storage: {{ default (ternary "100Gi" "200Gi" (eq .Values.nodes 3)) .Values.resources.requests.ephemeralStorage }}
            limits:
              cpu:    {{ default (ternary "2" "6" (eq .Values.nodes 3)) .Values.resources.limits.cpu }}
              memory: {{ default "32Gi" .Values.resources.limits.memory }}
              ephemeral-storage: {{ default (ternary "100Gi" "200Gi" (eq .Values.nodes 3)) .Values.resources.limits.ephemeralStorage }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/system_bus_socket
            type: Socket
        - name: run-tmpfs
          emptyDir:
            medium: Memory
        - name: tmpfs
          emptyDir:
            medium: Memory
        - name: command-configmap
          configMap:
            name: "{{ .Release.Name }}-command"

